export interface User {
  name:String,
  surname: String,
  adress: String,
  city: String,
  country: String,
  pc: String,
  email:String,
  password: String,
  pic: String,
  favoriteBuddy: Array<string>,
  dogBuddy: Boolean, 
  infoBuddy: String,
  rateBuddy: Number,
  petsBuddy: String,
  houseBuddy: String,
  zonesBuddy: String,
}